# Generated by Django 5.2 on 2025-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=50, null=True),
        ),
    ]
