# Generated by Django 5.2 on 2025-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_address',
            field=models.CharField(default='Baneshwor, Kathmandu', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_phone',
            field=models.CharField(default='9800000000', max_length=255),
        ),
    ]
