# Generated by Django 5.2 on 2025-04-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_pickup_address_product_pickup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
